### ISSUE TITLE
401 Unauthorized response does not return CORS headers

### ISSUE THREAD

**Issue by sjsikkema** [dionsnoeijen/sexy-field#70]
Usually responses return the `Access-Control-Allow-Origin` header, with `*` or the origin that was sent in the request, to support standalone web applications. This works when authenticated, but on the 401 Unauthorized, this header is not present in the response headers.

**Comment by dionsnoeijen** [comment]
Is this not meanth for the devstack? SexyField doesn't know about authentication or authorization.

**Comment by sjsikkema** [comment]
Yes you are right. I will close this issue and create a new issue on our own board.
